version: '2'
volumes:
  sonarqube-app-data:
    driver: ${volumedriver}
  sonarqube-conf-data:
    driver: ${volumedriver}
  sonarqube-plugin-data:
    driver: ${volumedriver}
services:    
    sonarqube:
      ports:
      - 9000:9000/tcp
      environment:
        SONARQUBE_JDBC_USERNAME: ${sonarqube_db_login}
        SONARQUBE_JDBC_PASSWORD: ${sonarqube_db_password}
        SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonar
      labels:
        io.rancher.sidekicks: sonarqube-datavolume,sonarqube-plugin
      external_links:
      - ${postgres_link}:postgres
      tty: true
      image: sonarqube:7.1
      volumes_from:
      - sonarqube-plugin  
      stdin_open: true    
    sonarqube-plugin:
      labels:
        io.rancher.container.start_once: true
      tty: true
      #  build: .
      image: busybox
      #image: rameshkumara/sonarqube-plugin:1.0
      command: wget -P /opt/sonarqube/extensions/plugins/ ${plugins} 
      container_name: sonarqube-plugin
      volumes: 
      - sonarqube-plugin-data:/opt/sonarqube/extensions/plugins   
    sonarqube-datavolume:
      labels:
        io.rancher.container.start_once: 'true'
      tty: true
      image: busybox
      volumes:
      - sonarqube-app-data:/opt/sonarqube/data
      - sonarqube-conf-data:/opt/sonarqube/conf
      stdin_open: true
