version: '2'
.catalog:
  name: "Monitoring Agent App"
  version: "Monitoring-Agent-1.0"
  description: "Monitoring Agent Application"
  questions:
  - variable: "AGENT_NAME"
    label: "Name Of the Agent/Client :"
    description: "Name Of the Agent/Client(space not allowed)"
    default: "Demo-Agent"
    required: true
    type: "string"    
  - variable: "SUBSCRIPTIONS_LIST"
    label: " Subcrption list :"
    description: "Subcrption list from sensu server"
    default: "system,sites"
    required: true
    type: "string"    
  - variable: "AGENT_ADDRESS"
    label: " Agent Address :"
    description: "Agent Address (for infromation only)"
    default: ""
    required: true
    type: "string"
  - variable: "redis_link"
    description: stack/service link or external service link to Redis DB from Sensu.
    label: "Redis stack/service"
    required: true
    type: "service" 