version: '2'
.catalog:
  name: "Monitoring App "
  version: "Monitoring-1.1"
  description: "Sensu ,influxdb ,grafana application"
  questions:
  - variable: "configuration_repo_path"
    label: "Configuration Repo Path:"
    description: "Path to repo which contains monitoring configs"
    required: true
    type: "string"
    default: "https://gitlab.dynamictivity.com/rosetta/monitoring-conf-repo"
  - variable: "influxdb_admin_password"
    label: "InfluxDB Admin Password:"
    description: "InfluxDB Admin Password"
    required: true
    type: "password"
  - variable: "influxdb_db_password"
    label: "InfluxDB Metric DB Password:"
    description: "InfluxDB Metric Database Password"
    required: true
    type: "password"
  - variable: "mattermost_username"
    label: "MatterMost User Name:"
    description: "MatterMost User Name , used in mattermost handler"
    required: true
    type: "string"
  - variable: "mattermost_url"
    label: "Mattermost Hook URL :"
    description: "Mattermost Hook URL used in mattermost handler"
    default: "https://mattermost.example.com/hooks/xxxxxxxxxxxx"
    required: true
    type: "multiline"
  - variable: "grafana_datasource_path"
    label: "Grafana Datasource Location:"
    description: "Location of Grafana Datasource yaml"
    default: "https://gitlab.dynamictivity.com/rosetta/monitoring-conf-repo/raw/master/datasource/datasource.yaml"
    required: true
    type: "multiline"
  - variable: "grafana_dashboard_path"
    label: "Grafana Dashboard Location:"
    description: "Location of Grafana Dashboard yaml"
    default: "https://gitlab.dynamictivity.com/rosetta/monitoring-conf-repo/raw/master/dashboard/dashboard.yaml"
    required: true
    type: "multiline"
  - variable: "grafana_dashboard_json"
    label: "List of Grafana Dashboards Location :"
    description: "List of location of Grafana Dashboard JSON"
    default: "https://gitlab.dynamictivity.com/rosetta/monitoring-conf-repo/raw/master/dashboard/grafana-config.json"
    required: true
  - variable: "service_tld"
    label: "Service TLD:"
    description: "Domain to register"
    default: "example.com"
    required: true
    type: "string"
  - variable: "uchiwa_subdomain"
    label: "Uchiwa Subdomain:"
    description: "Uchiwa Dashboard Subdomain"
    default: "uchiwa"
    required: true
    type: "string"
  - variable: "grafana_subdomain"
    label: "Grafana Subdomain:"
    description: "Grafana DNS Subdomain"
    default: "grafana"
    required: true
    type: "string"
  - variable: "influxdb_subdomain"
    label: "InfluxDB Subdomain:"
    description: "influxdb DNS Subdomain"
    default: "influxdb"
    required: true
    type: "string"
  - variable: "default_check_url"
    label: "Default Check URL:"
    description: "Host need to be monitored"
    default: "https://sonarqube.example.com"
    required: true
    type: "string"
  - variable: "default_check_name"
    label: "Default Check Name:"
    description: "Check Name for Site"
    default: "SonarQube_check"
    required: true
    type: "string"
  - variable: "datacenter_name"
    label: "Datacenter Name:"
    description: "Data Center Name"
    default: "Demo-DC"
    required: true
    type: "string"
  - variable: "volumedriver"
    description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
    label: "Volume Driver:"
    required: true
    default: local
    type: "enum"
    options:
      - local
      - rancher-nfs
