# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#        ___         __  _ ____           __                  
#       /   |  _____/ /_(_) __/___ ______/ /_____  _______  __
#      / /| | / ___/ __/ / /_/ __ `/ ___/ __/ __ \/ ___/ / / /
#     / ___ |/ /  / /_/ / __/ /_/ / /__/ /_/ /_/ / /  / /_/ / 
#    /_/  |_/_/   \__/_/_/  \__,_/\___/\__/\____/_/   \__, /  
#                                                    /____/                                                
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

version: '2'
services:
  postgresql:
    restart: always
    image: docker.bintray.io/postgres:9.5.2
    ports:
     - 5432:5432
    environment:
       POSTGRES_DB: artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
       POSTGRES_USER: artifactory
       POSTGRES_PASSWORD: password
    volumes:
     - /data/postgresql:/var/lib/postgresql/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  artifactory:
    restart: always
    image: docker.bintray.io/jfrog/artifactory-pro:5.8.3
    ports:
     - "0.0.0.0:8081:8081"
    depends_on:
     - postgresql
    links:
     - postgresql
    environment:
       DB_TYPE: postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
       DB_USER: artifactory
       DB_PASSWORD: password
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory 
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
